### ISSUE TITLE
NTSC Krill support?!

### ISSUE THREAD

**Issue by jpcompton** [thierer/sd2iec#2]
As mentioned in email, https://csdb.dk/release/?id=188012 fails to run properly load (on my NTSC 64C, uIEC v3.2) with the exact same issue you can replicate in a VICE NTSC instance by turning off True Drive emulation, ala:

<img width="688" alt="Screen Shot 2022-10-03 at 8 19 34 PM" src="https://user-images.githubusercontent.com/51372049/193833539-4fe23cf4-a1fa-42af-9449-14043ecd639c.png">

But this raises a trickier question... just what other Krill loader titles are there which actually work on NTSC? It would be nice to test a few as we iterate through these improvements, if we can _find_ a few...

**Comment by thierer** [comment]
I think it's a long shot to blame that on NTSC. Could well be a fallout of #1.

FWIW, it works for me with the MiSTer C64 core when I select NTSC video. Don't know how significant that is, though.

First check: Does it work from a real disk in a 1541?

Regarding productions using Krill's see the table at the end of [krills-loader.txt](https://github.com/thierer/sd2iec/blob/master/doc/krills-loader.txt). No idea which of these are supposed to be NTSC ready, though.

**Comment by jpcompton** [comment]
I thought since you mentioned this title specifically that you considered it a known-good Krill-loading game on your firmware. Which would mean it works on PAL machines hitting Thierer-sd2iec firmware, but (according to me), not NTSC machines doing so.

Am I missing something?

> FWIW, it works for me with the MiSTer C64 core when I select NTSC video. Don't know how significant that is, though.

Not familiar with MiSTer, are you using true 1541 emulation or not? (Or are you connecting the sd2iec to the MiSTer? Is that even possible?)

WITH true 1541 emulation, this works on VICE and I expect this to work on real floppy (will test later)
WITHOUT true 1541 emulation, I expect it to fail.

**Comment by jpcompton** [comment]
And yes I tried asking on CSDB for a list of known-good-NTSC Krill loader games and got nowhere, so.

**Comment by thierer** [comment]
> I thought since you mentioned this title specifically that you considered it a known-good Krill-loading game on your firmware.

I just mentioned it because you mentioned the NOS version :) And yes, it's "known-good" in that in works for me, but I didn't think of PAL vs. NTSC at the time. And if it doesn't work on NTSC I'd blame it on the production first, not necessarily the sd2iec :)

> Not familiar with MiSTer, are you using true 1541 emulation or not? (Or are you connecting the sd2iec to the MiSTer? Is that even possible?)

Yes, I connect the sd2iec to the MiSTer, it can drive an external IEC bus. You need some adapter with a level shifter, but then it works great.

> WITH true 1541 emulation, this works on VICE and I expect this to work on real floppy (will test later)

Yes, that would be helpful. Thanks!

**Comment by jpcompton** [comment]
(as noted in email, your test rev 59 allows this Psi-5 to load properly on NTSC. Would be happy to test other Krill-loader-programs, if we can identify any!)

**Comment by thierer** [comment]
Closing, as my understanding is that it really was the same underlying issue as #1. Plus, until proven otherwise, I'd consider lack of support for NTSC (or PAL, for that matter) to be an issue of the respective production, not the sd2iec firmware.
